### ISSUE TITLE
Use Trait instead of free functions

### ISSUE THREAD

**Issue by Piroro-hs** [HamaguRe/quaternion-core#1]
Also please consider publishing this crate on crates.io.

**Comment by HamaguRe** [comment]
Thanks for the Issue! And sorry for not replying for a long time.

First of all, I changed the name of the crate to `quaternion-core` and [published it on crates.io!](https://crates.io/crates/quaternion-core) (since the quaternion crate already existed)

Second, regarding the suggestion of using a trait, it is possible to implement a trait for a quaternion<T> (like q.conj()), but not operator overloading, so I left this function implementation as it is and create a new crate as a `quaternion-wrapper`.
I've [published this one on crates.io](https://crates.io/crates/quaternion-wrapper) as well, so I hope you'll try it!

I don't know if this is what you had in mind, but I have settled on the current implementation.
